app:
  baseUrl: https://demo.backstage.io

backend:
  baseUrl: https://demo.backstage.io
  listen:
    port: ${PORT}
  auth:
    keys:
      - secret: ${BACKEND_AUTH_KEY}

auth:
  environment: production
  experimentalExtraAllowedOrigins:
    - https://pr-+(0|1|2|3|4|5|6|7|8|9)-deployment-+(0|1|2|3|4|5|6|7|8|9)-backstage.app.uffizzi.com
  providers:
    github:
      production:
        clientId: ${GITHUB_PRODUCTION_CLIENT_ID}
        clientSecret: ${GITHUB_PRODUCTION_CLIENT_SECRET}

techdocs:
  requestUrl: https://demo.backstage.io/api/techdocs
  storageUrl: https://demo.backstage.io/api/techdocs/static/docs
  builder: 'external'
  generators:
    techdocs: local
  publisher:
    type: 'googleGcs'
    googleGcs:
      credentials: ${TECHDOCS_GCS_CREDENTIALS}
      projectId: ${TECHDOCS_GCS_PROJECT_ID}
      bucketName: ${TECHDOCS_GCS_BUCKET}